### ISSUE TITLE
Page: Quiz 🎮

### ISSUE THREAD

**Issue by ArmandoShala** [ArmandoShala/FILMREEL#2]
**Baseline**
On the quiz page a short trailer clip of a movie is shown. The users have limited time to watch the short film clip. After that, the timer starts and the quiz duel for this movie clip begins. Below the film section, various questions and corresponding answers are listed, which the players have to decide on as quickly as possible. The faster the answer, the more points you get. After the question has been answered or the timer has run out, the game switches to the scoreboard and the points are displayed as an intermediate score. The person who has collected more points during the game wins the duel. This procedure is similar to the Kahoot procedure.

**Problem**
N/A

**Requirement**
- [ ] There needs to be a points counter (more like a timer)
- [ ] Autoplay a move without any further information
- [ ] Show questions regarding the movie (Title, Release Year, Main Actors, virtually anything about the provided information)
- [ ] If there are two players: One can change the answer only until the other hasn't answered yet.
- [ ] As soon as all parties gave answer, the answers are locked and the game procedures to the next screen #4

**Possible way of implementation / solution**
Refer Figma for a possible implementation

**Hints**
N/A

**Comment by landrit** [comment]
I see a problem on what do we do when a user accidentally selects the answer of the other user? 
Do we let them to unselect answers?

**Comment by omerasipi** [comment]
No we play game mode "hardcore" 😈
