### ISSUE TITLE
Page: Scoreboard 💯

### ISSUE THREAD

**Issue by landrit** [ArmandoShala/FILMREEL#4]
**Baseline**
After each question from #2 , the current scoreboard is displayed. Here you can see who is ahead in the race. In addition, the players have the option of viewing further details on the film displayed before, ending the quiz or adding the film to the watchlist by swiping. A right swipe on the scoreboard puts the movie on the watchlist. Swiping left discards the movie. Swipe up to indicate that you have already seen the movie, but still want it on the watchlist. Last but not least, you can swipe down, so that the film is added to the watchlist, but is already marked as watched.

**Problem**
How do you calculate the points of the users? Where are the points stored? 

**Requirement**

- [ ] Add the buttons that stops the quiz and that let you see the leaderboard as well as the button that lets you continue with quizzes. 
- [ ] Write an algorithm that calculates the points of the users and list them
- [ ] Show the previous seen movie with a button that lets you see more details to this movie
- [ ] Show the previous question and the right answer

**Possible way of implementation / solution**
1. Pass the question from the previous page to this page and load the right answer from the database
2. Add two buttons that lets you get to the leaderboard and that finishes the quiz as well as the button that continues with quizzes.

**Hints**
N/A
