### ISSUE TITLE
Basic App Structure

### ISSUE THREAD

**Issue by omerasipi** [ArmandoShala/FILMREEL#6]
**Is your feature request related to a problem? Please describe.**
To start developing the oncoming issues, we need some sort of basic structure for our app. Everything is going to be built up on that and therefore this is a very important issue.

**Describe the solution you'd like**
Develop the basic App structure like this:
![image](https://user-images.githubusercontent.com/39113466/193354839-defac9da-9acd-42b8-93d3-8c4141c5a1c9.png)

Body container:

- [ ] Container which is filled with the content of the current page/tab

Footer navbar:

- [ ] Container which displays all pages/tabs of the app
- [ ] Highlights the current used page/tab

Language:

- [ ] We need some sort of centralized language management, where all strings for Buttons, Tabs, etc. are saved.

**Describe alternatives you've considered**
Maybe a optional header with our logo could be useful

**Additional context**
